BUILD := debug

TARGET_CC_SOURCES += itrlib/itrpriv.c

TARGET_CMOCKA_CC_SOURCES += tests/cmocka/itrlib_test.c
TARGET_CMOCKA_CC_SOURCES += $(TARGET_CC_SOURCES)

TARGET_GTEST_CC_SOURCES += $(TARGET_CC_SOURCES)